# Generated by Django 4.2.13 on 2024-07-07 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['title']},
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('unit_of_measure', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ingredient', models.CharField(max_length=5)),
                ('notes', models.CharField(max_length=50, default=None, blank=True, null=True)),
                ('recipe', models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, to='a_recipes.recipe')),
            ],
        ),
    ]
